// apps/comparison/src/components/react/ComparisonIsland.jsx
import { Fragment, jsx, jsxs } from "react/jsx-runtime";
// Keep this module JSX-free. Vite dev import-analysis currently sees this
// client-script dependency before Astro's React JSX transform runs.
import { useMemo, useRef, useState } from "react";
import { Provider as SpectrumProvider } from "@react-spectrum/provider";
import { Button as SpectrumButton } from "@react-spectrum/button";
import {
  Item as SpectrumItem,
  TabList as SpectrumTabList,
  TabPanels as SpectrumTabPanels,
  Tabs as SpectrumTabs
} from "@react-spectrum/tabs";
import { theme as defaultTheme } from "@react-spectrum/theme-default";
import {
  Button as RACButton,
  Calendar as RACCalendar,
  CalendarCell as RACCalendarCell,
  CalendarGrid as RACCalendarGrid,
  Checkbox as RACCheckbox,
  DateInput as RACDateInput,
  DatePicker as RACDatePicker,
  DateSegment as RACDateSegment,
  Dialog as RACDialog,
  DialogTrigger as RACDialogTrigger,
  Group as RACGroup,
  Heading as RACHeading,
  Input as RACInput,
  Label as RACLabel,
  ListBox as RACListBox,
  ListBoxItem as RACListBoxItem,
  Modal as RACModal,
  ModalOverlay as RACModalOverlay,
  Popover as RACPopover,
  Radio as RACRadio,
  RadioGroup as RACRadioGroup,
  SearchField as RACSearchField,
  Select as RACSelect,
  SelectValue as RACSelectValue,
  Tab as RACTab,
  TabList as RACTabList,
  TabPanel as RACTabPanel,
  Tabs as RACTabs,
  TextField as RACTextField,
  Toolbar as RACToolbar,
  Tooltip as RACTooltip,
  TooltipTrigger as RACTooltipTrigger,
  ToggleButton as RACToggleButton
} from "react-aria-components";
import { UNSAFE_PortalProvider, useButton } from "react-aria";
const tabItems = [
  {
    key: "overview",
    label: "Overview",
    content: "Overlay dismissal now respects the local portal scope."
  },
  {
    key: "parity",
    label: "Parity",
    content: "Collection composition is the main remaining styled-layer nuance."
  },
  {
    key: "testing",
    label: "Testing",
    content: "This page is intended to become a Playwright and axe target."
  }
];
const selectItems = [
  { id: "alpha", label: "Alpha" },
  { id: "bravo", label: "Bravo" },
  { id: "charlie", label: "Charlie" }
];
function ComparisonIsland(props) {
  const overlayRootRef = useRef(null);
  return /* @__PURE__ */ jsxs("div", { className: "comparison-island", children: [
    /* @__PURE__ */ jsx(
      UNSAFE_PortalProvider,
      {
        getContainer: () => overlayRootRef.current ?? document.body,
        children: renderLayer(props)
      }
    ),
    /* @__PURE__ */ jsx("div", { ref: overlayRootRef, className: "comparison-overlay-root" })
  ] });
}
function renderLayer({ componentSlug, layer }) {
  if (layer === "styled") {
    return renderStyled(componentSlug);
  }
  if (layer === "components") {
    return renderComponents(componentSlug);
  }
  if (layer === "headless") {
    return renderHeadless(componentSlug);
  }
  return /* @__PURE__ */ jsx("div", { className: "comparison-empty-state", children: "This layer is tracked in the manifest but not rendered yet." });
}
function renderStyled(componentSlug) {
  switch (componentSlug) {
    case "provider":
      return /* @__PURE__ */ jsx(
        SpectrumProvider,
        {
          theme: defaultTheme,
          colorScheme: "dark",
          UNSAFE_style: providerShellStyle,
          children: /* @__PURE__ */ jsxs("div", { className: "comparison-provider-stack", children: [
            /* @__PURE__ */ jsx("div", { className: "comparison-provider-caption", children: "Outer provider: dark / medium scale" }),
            /* @__PURE__ */ jsx(SpectrumButton, { variant: "primary", children: "Inherited Action" }),
            /* @__PURE__ */ jsxs(
              SpectrumProvider,
              {
                theme: defaultTheme,
                colorScheme: "light",
                UNSAFE_style: nestedProviderStyle,
                children: [
                  /* @__PURE__ */ jsx("div", { className: "comparison-provider-caption", children: "Nested provider: local light override" }),
                  /* @__PURE__ */ jsx(SpectrumButton, { variant: "accent", children: "Nested Override" })
                ]
              }
            )
          ] })
        }
      );
    case "button":
      return /* @__PURE__ */ jsx(
        SpectrumProvider,
        {
          theme: defaultTheme,
          colorScheme: "dark",
          UNSAFE_style: providerShellStyle,
          children: /* @__PURE__ */ jsxs("div", { className: "comparison-button-row", children: [
            /* @__PURE__ */ jsx(SpectrumButton, { variant: "primary", children: "Primary" }),
            /* @__PURE__ */ jsx(SpectrumButton, { variant: "accent", children: "Accent" }),
            /* @__PURE__ */ jsx(SpectrumButton, { variant: "secondary", children: "Secondary" })
          ] })
        }
      );
    case "tabs":
      return /* @__PURE__ */ jsx(
        SpectrumProvider,
        {
          theme: defaultTheme,
          colorScheme: "dark",
          UNSAFE_style: providerShellStyle,
          children: /* @__PURE__ */ jsxs(SpectrumTabs, { "aria-label": "React Spectrum tabs", maxWidth: 360, children: [
            /* @__PURE__ */ jsx(SpectrumTabList, { children: tabItems.map((item) => /* @__PURE__ */ jsx(SpectrumItem, { children: item.label }, item.key)) }),
            /* @__PURE__ */ jsx(SpectrumTabPanels, { children: tabItems.map((item) => /* @__PURE__ */ jsx(SpectrumItem, { children: item.content }, item.key)) })
          ] })
        }
      );
    case "textfield":
      return /* @__PURE__ */ jsx(ReactTextFieldDemo, {});
    case "select":
      return /* @__PURE__ */ jsx(ReactSelectDemo, {});
    case "checkbox":
      return /* @__PURE__ */ jsx(RACCheckbox, { className: "comparison-check", children: "Enable alerts" });
    case "dialog":
      return /* @__PURE__ */ jsx(ReactDialogDemo, {});
    case "radio":
      return /* @__PURE__ */ jsx(ReactRadioDemo, {});
    case "datepicker":
      return /* @__PURE__ */ jsx(ReactDatePickerDemo, {});
    case "searchfield":
      return /* @__PURE__ */ jsx(ReactSearchFieldDemo, {});
    case "tooltip":
      return /* @__PURE__ */ jsx(ReactTooltipDemo, {});
    case "toolbar":
      return /* @__PURE__ */ jsx(ReactToolbarDemo, {});
    case "toast":
      return /* @__PURE__ */ jsx("div", { className: "comparison-empty-state", children: "React Aria Components 1.15.1 does not expose Toast." });
    default:
      return /* @__PURE__ */ jsx("div", { className: "comparison-empty-state", children: "No styled React Spectrum demo is wired for this component yet." });
  }
}
function ReactTextFieldDemo() {
  return /* @__PURE__ */ jsxs(RACTextField, { className: "comparison-form-control", defaultValue: "Quarterly report", children: [
    /* @__PURE__ */ jsx(RACLabel, { children: "Name" }),
    /* @__PURE__ */ jsx(RACInput, {})
  ] });
}
function ReactSelectDemo() {
  const [selectedKey, setSelectedKey] = useState("bravo");
  return /* @__PURE__ */ jsx("div", { className: "comparison-spectrum-skin", "data-comparison-selected-key": selectedKey, children: /* @__PURE__ */ jsxs(
    RACSelect,
    {
      className: "comparison-spectrum-Select",
      defaultSelectedKey: "bravo",
      onSelectionChange: (key) => {
        setSelectedKey(key == null ? "" : String(key));
      },
      children: [
        /* @__PURE__ */ jsx(RACLabel, { className: "comparison-spectrum-Field-label", "data-slot": "label", children: "Channel" }),
        /* @__PURE__ */ jsx(
          RACButton,
          {
            className: "comparison-spectrum-Field-input comparison-spectrum-Select-trigger",
            children: /* @__PURE__ */ jsx(RACSelectValue, { className: "comparison-spectrum-Select-value", "data-slot": "value" })
          }
        ),
        /* @__PURE__ */ jsx(
          RACPopover,
          {
            className: "comparison-popover",
            children: /* @__PURE__ */ jsx(
              RACListBox,
              {
                className: "comparison-spectrum-Select-listbox",
                children: selectItems.map((item) => /* @__PURE__ */ jsx(
                  RACListBoxItem,
                  {
                    id: item.id,
                    className: "comparison-spectrum-Select-option",
                    children: item.label
                  },
                  item.id
                ))
              }
            )
          }
        )
      ]
    }
  ) });
}
function ReactDialogDemo() {
  return /* @__PURE__ */ jsx("div", { className: "comparison-spectrum-skin", children: /* @__PURE__ */ jsxs(RACDialogTrigger, { children: [
    /* @__PURE__ */ jsx(RACButton, { className: "comparison-spectrum-Button", "data-variant": "primary", "data-style": "outline", children: "Open Dialog" }),
    /* @__PURE__ */ jsx(RACModalOverlay, { className: "comparison-dialog-underlay", isDismissable: true, children: /* @__PURE__ */ jsx("div", { className: "comparison-dialog-positioner", children: /* @__PURE__ */ jsx(RACModal, { className: "comparison-dialog-modal", children: /* @__PURE__ */ jsx(RACDialog, { className: "comparison-dialog-surface comparison-spectrum-Dialog", children: ({ close }) => /* @__PURE__ */ jsxs(Fragment, { children: [
      /* @__PURE__ */ jsx(RACHeading, { slot: "title", className: "comparison-spectrum-Dialog-title", children: "Review Changes" }),
      /* @__PURE__ */ jsx("p", { className: "comparison-spectrum-Dialog-body", children: "Dialog focus and dismissal are compared from this island." }),
      /* @__PURE__ */ jsx(RACButton, { className: "comparison-spectrum-Dialog-closeButton", "aria-label": "Close dialog", onPress: close, children: /* @__PURE__ */ jsx("svg", { "aria-hidden": "true", viewBox: "0 0 24 24", fill: "none", stroke: "currentColor", strokeWidth: 2, strokeLinecap: "round", strokeLinejoin: "round", children: /* @__PURE__ */ jsxs(Fragment, { children: [
        /* @__PURE__ */ jsx("path", { d: "M18 6 6 18" }),
        /* @__PURE__ */ jsx("path", { d: "m6 6 12 12" })
      ] }) }) })
    ] }) }) }) }) })
  ] }) });
}
function ReactRadioDemo() {
  return /* @__PURE__ */ jsxs(RACRadioGroup, { className: "comparison-form-control", defaultValue: "compact", "aria-label": "Density", children: [
    /* @__PURE__ */ jsx(RACLabel, { children: "Density" }),
    /* @__PURE__ */ jsx(RACRadio, { value: "compact", className: "comparison-check", children: "Compact" }),
    /* @__PURE__ */ jsx(RACRadio, { value: "comfortable", className: "comparison-check", children: "Comfortable" })
  ] });
}
function ReactDatePickerDemo() {
  const [value, setValue] = useState("");
  const [isOpen, setIsOpen] = useState(false);
  return /* @__PURE__ */ jsx("div", { className: "comparison-spectrum-skin comparison-stack", "data-comparison-value": value, "data-comparison-open": String(isOpen), children: /* @__PURE__ */ jsxs(RACDatePicker, { className: "comparison-form-control comparison-datepicker-root", "aria-label": "Due date", onChange: (nextValue) => setValue(nextValue == null ? "" : String(nextValue)), onOpenChange: setIsOpen, children: [
    /* @__PURE__ */ jsx(RACLabel, { className: "comparison-spectrum-Field-label", "data-slot": "label", children: "Due date" }),
    /* @__PURE__ */ jsxs(RACGroup, { className: "comparison-datepicker-group", children: [
      /* @__PURE__ */ jsx(RACDateInput, { className: "comparison-date-input", children: (segment) => /* @__PURE__ */ jsx(RACDateSegment, { segment }) }),
      /* @__PURE__ */ jsx(RACButton, { className: "comparison-field-button", children: "Calendar" })
    ] }),
    /* @__PURE__ */ jsx(RACPopover, { className: "comparison-popover comparison-datepicker-popover", children: /* @__PURE__ */ jsx(RACDialog, { className: "comparison-popover-dialog", children: /* @__PURE__ */ jsxs(RACCalendar, { children: [
      /* @__PURE__ */ jsxs("header", { className: "comparison-datepicker-header", children: [
        /* @__PURE__ */ jsx(RACButton, { slot: "previous", className: "comparison-rac-button", children: "Previous" }),
        /* @__PURE__ */ jsx(RACHeading, { className: "comparison-popover-title" }),
        /* @__PURE__ */ jsx(RACButton, { slot: "next", className: "comparison-rac-button", children: "Next" })
      ] }),
      /* @__PURE__ */ jsx(RACCalendarGrid, { children: (date) => /* @__PURE__ */ jsx(RACCalendarCell, { date }) })
    ] }) }) })
  ] }) });
}
function ReactSearchFieldDemo() {
  const [value, setValue] = useState("status");
  const [clearCount, setClearCount] = useState(0);
  return /* @__PURE__ */ jsx("div", { className: "comparison-stack", "data-comparison-input-value": value, "data-comparison-clear-count": String(clearCount), children: /* @__PURE__ */ jsxs(RACSearchField, { className: "comparison-form-control", defaultValue: "status", onChange: setValue, onClear: () => {
    setValue("");
    setClearCount((count) => count + 1);
  }, children: [
    /* @__PURE__ */ jsx(RACLabel, { children: "Search" }),
    /* @__PURE__ */ jsx(RACInput, {}),
    /* @__PURE__ */ jsx(RACButton, { className: "comparison-rac-button", children: "Clear search" })
  ] }) });
}
function ReactTooltipDemo() {
  return /* @__PURE__ */ jsxs(RACTooltipTrigger, { isOpen: true, children: [
    /* @__PURE__ */ jsx(RACButton, { className: "comparison-rac-button", children: "Inspect" }),
    /* @__PURE__ */ jsx(RACTooltip, { className: "comparison-tooltip", children: "Tooltip content" })
  ] });
}
function ReactToolbarDemo() {
  const [boldPressed, setBoldPressed] = useState(false);
  const [actionCount, setActionCount] = useState(0);
  return /* @__PURE__ */ jsx("div", { className: "comparison-stack", "data-comparison-pressed": String(boldPressed), "data-comparison-action-count": String(actionCount), children: /* @__PURE__ */ jsxs(RACToolbar, { className: "comparison-toolbar", "aria-label": "Formatting tools", children: [
    /* @__PURE__ */ jsx(RACToggleButton, { className: "comparison-rac-button", isSelected: boldPressed, onChange: (selected) => {
      setBoldPressed(selected);
      setActionCount((count) => count + 1);
    }, children: "Bold" }),
    /* @__PURE__ */ jsx(RACButton, { className: "comparison-rac-button", children: "Italic" })
  ] }) });
}
function renderComponents(componentSlug) {
  switch (componentSlug) {
    case "button":
      return /* @__PURE__ */ jsxs("div", { className: "comparison-stack", children: [
        /* @__PURE__ */ jsx(RACButton, { className: "comparison-rac-button", children: "Component Button" }),
        /* @__PURE__ */ jsx(
          RACButton,
          {
            isDisabled: true,
            className: "comparison-rac-button comparison-rac-button--muted",
            children: "Disabled by props"
          }
        )
      ] });
    case "popover":
      return /* @__PURE__ */ jsx("div", { className: "comparison-stack", children: /* @__PURE__ */ jsxs(RACDialogTrigger, { children: [
        /* @__PURE__ */ jsx(RACButton, { className: "comparison-rac-button", children: "Open Popover" }),
        /* @__PURE__ */ jsx(RACPopover, { className: "comparison-popover", children: /* @__PURE__ */ jsxs(
          RACDialog,
          {
            "aria-label": "Quick audit note",
            className: "comparison-popover-dialog",
            children: [
              /* @__PURE__ */ jsx(RACHeading, { slot: "title", className: "comparison-popover-title", children: "Confirm Action" }),
              /* @__PURE__ */ jsx("p", { children: "Outside press and escape should dismiss this overlay without escaping its local comparison root." })
            ]
          }
        ) })
      ] }) });
    case "tabs":
      return /* @__PURE__ */ jsxs(RACTabs, { className: "comparison-rac-tabs", "aria-label": "React Aria tabs", children: [
        /* @__PURE__ */ jsx(RACTabList, { className: "comparison-rac-tab-list", children: tabItems.map((item) => /* @__PURE__ */ jsx(
          RACTab,
          {
            id: item.key,
            className: "comparison-rac-tab",
            children: item.label
          },
          item.key
        )) }),
        tabItems.map((item) => /* @__PURE__ */ jsx(
          RACTabPanel,
          {
            id: item.key,
            className: "comparison-tabs-panel",
            children: item.content
          },
          item.key
        ))
      ] });
    default:
      return /* @__PURE__ */ jsx("div", { className: "comparison-empty-state", children: "No component-layer React demo is wired for this component yet." });
  }
}
function renderHeadless(componentSlug) {
  switch (componentSlug) {
    case "button":
      return /* @__PURE__ */ jsx(ReactHeadlessButtonDemo, {});
    default:
      return /* @__PURE__ */ jsx("div", { className: "comparison-empty-state", children: "No headless React demo is wired for this component yet." });
  }
}
function ReactHeadlessButtonDemo() {
  const ref = useRef(null);
  const [pressCount, setPressCount] = useState(0);
  const { buttonProps, isPressed } = useButton(
    {
      onPress: () => setPressCount((count) => count + 1),
      "aria-label": "Headless action"
    },
    ref
  );
  const label = useMemo(() => {
    if (isPressed) {
      return "Pressed";
    }
    return `Pressed ${pressCount} times`;
  }, [isPressed, pressCount]);
  return /* @__PURE__ */ jsxs("div", { className: "comparison-headless-stack", children: [
    /* @__PURE__ */ jsx(
      "button",
      {
        ...buttonProps,
        ref,
        type: "button",
        className: "comparison-headless-button",
        children: label
      }
    ),
    /* @__PURE__ */ jsx("p", { className: "comparison-helper-copy", children: "This uses the raw `useButton` hook rather than a pre-wired component." })
  ] });
}
const providerShellStyle = {
  padding: 20,
  borderRadius: 18,
  background: "linear-gradient(180deg, rgba(7, 14, 22, 0.92), rgba(8, 22, 38, 0.78))"
};
const nestedProviderStyle = {
  padding: 16,
  marginTop: 16,
  borderRadius: 16
};
export {
  ComparisonIsland as default
};

// apps/comparison/src/components/solid/ComparisonIsland.tsx
import h from "solid-js/h";
import { createMemo, createSignal, onCleanup, onMount } from "solid-js";
import { hc, renderProp } from "./solid-h";
import { Provider as SilapseProvider } from "@proyecto-viviana/silapse";
import {
  Button as SilapseButton,
  Checkbox,
  Dialog,
  Radio,
  RadioGroup,
  SearchField,
  Tab,
  TabList,
  TabPanel,
  Tabs,
  ToastProvider,
  ToastRegion,
  Toolbar,
  Tooltip,
  TooltipTrigger,
  ToggleButton,
  addToast,
  globalToastQueue,
} from "@proyecto-viviana/silapse";
import {
  Button as HeadlessButton,
  DialogTrigger as HeadlessDialogTrigger,
  Popover as HeadlessPopover,
  PopoverTrigger as HeadlessPopoverTrigger,
  Calendar as HeadlessCalendar,
  CalendarButton as HeadlessCalendarButton,
  CalendarCell as HeadlessCalendarCell,
  CalendarGrid as HeadlessCalendarGrid,
  CalendarHeading as HeadlessCalendarHeading,
  DateInput as HeadlessDateInput,
  DatePicker as HeadlessDatePicker,
  DatePickerButton as HeadlessDatePickerButton,
  DatePickerContent as HeadlessDatePickerContent,
  DatePickerLabel as HeadlessDatePickerLabel,
  DateSegment as HeadlessDateSegment,
  Input as HeadlessInput,
  Label as HeadlessLabel,
  Modal as HeadlessModal,
  ModalOverlay as HeadlessModalOverlay,
  Select as HeadlessSelect,
  SelectListBox as HeadlessSelectListBox,
  SelectOption as HeadlessSelectOption,
  SelectTrigger as HeadlessSelectTrigger,
  SelectValue as HeadlessSelectValue,
  Tab as HeadlessTab,
  TabList as HeadlessTabList,
  TabPanels as HeadlessTabPanels,
  TabPanel as HeadlessTabPanel,
  Tabs as HeadlessTabs,
  TextField as HeadlessTextField,
} from "@proyecto-viviana/solidaria-components";
import {
  createButton,
  UNSAFE_PortalProvider,
} from "@proyecto-viviana/solidaria";
import type {
  ComparisonLayerId,
  ComparisonSlug,
} from "@comparison/data/comparison-manifest";
import {
  comparisonReferenceDataset,
  comparisonSelectItems as selectItems,
  comparisonSpectrumSkin,
  comparisonTabItems as tabItems,
  getComparisonReferenceKind,
  type ComparisonFramework,
  type ComparisonReferenceKind,
} from "@comparison/data/comparison-contract";

interface ComparisonIslandProps {
  componentSlug: ComparisonSlug;
  layer: ComparisonLayerId;
}

type TabItem = (typeof tabItems)[number];

export default function ComparisonIsland(props: ComparisonIslandProps) {
  let overlayRoot: HTMLDivElement | undefined;

  return h(
    "div",
    { class: "comparison-island" },
    h(
      UNSAFE_PortalProvider,
      { getContainer: () => overlayRoot ?? null },
      renderLayer(props),
    ),
    h("div", {
      class: "comparison-overlay-root",
      ref: (element: HTMLDivElement) => {
        overlayRoot = element;
      },
    }),
  )();
}

function renderLayer(props: ComparisonIslandProps) {
  let rendered;
  if (props.layer === "styled") {
    rendered = renderStyled(props.componentSlug);
  } else if (props.layer === "components") {
    rendered = renderComponents(props.componentSlug);
  } else if (props.layer === "headless") {
    rendered = renderHeadless(props.componentSlug);
  } else {
    rendered = emptyState("This layer is tracked in the manifest but not rendered yet.");
  }

  return comparisonReferenceFrame({
    componentSlug: props.componentSlug,
    framework: "solid",
    layer: props.layer,
    reference: getComparisonReferenceKind("solid", props.layer, props.componentSlug),
  }, rendered);
}

function comparisonReferenceFrame(
  input: {
    componentSlug: ComparisonSlug;
    framework: ComparisonFramework;
    layer: ComparisonLayerId;
    reference: ComparisonReferenceKind;
  },
  children: ReturnType<typeof h>,
) {
  return h(
    "div",
    {
      class: "comparison-reference-frame",
      ...comparisonReferenceDataset(input),
    },
    h("div", { class: "comparison-reference-canvas" }, children),
  );
}

function renderStyled(componentSlug: ComparisonSlug) {
  switch (componentSlug) {
    case "provider":
      return h(
        SilapseProvider,
        { colorScheme: "dark", style: providerShellStyle },
        h(
          "div",
          { class: "comparison-provider-stack" },
          h(
            "div",
            { class: "comparison-provider-caption" },
            "Outer provider: dark / medium scale",
          ),
          h(SilapseButton, { variant: "primary" }, "Inherited Action"),
          h(
            SilapseProvider,
            { colorScheme: "light", style: nestedProviderStyle },
            h(
              "div",
              { class: "comparison-provider-caption" },
              "Nested provider: local light override",
            ),
            h(SilapseButton, { variant: "accent" }, "Nested Override"),
          ),
        ),
      );
    case "button":
      return h(SolidariaSpectrumButtonDemo, {});
    case "tabs":
      return h(
        SilapseProvider,
        { colorScheme: "dark", style: providerShellStyle },
        h(
          Tabs,
          {
            items: tabItems,
            getKey: (item: TabItem) => item.id,
            getTextValue: (item: TabItem) => item.label,
          },
          h(
            TabList,
            { "aria-label": "Silapse tabs" },
            (item: TabItem) => h(Tab, { id: item.id }, item.label),
          ),
          tabItems.map((item) => h(TabPanel, { id: item.id }, item.content)),
        ),
      );
    case "textfield":
      return h(SolidariaSpectrumTextFieldDemo, {});
    case "select":
      return h(SolidariaSpectrumSelectDemo, {});
    case "checkbox":
      return h(SolidCheckboxDemo, {});
    case "dialog":
      return h(SolidDialogDemo, {});
    case "radio":
      return h(SolidRadioDemo, {});
    case "datepicker":
      return h(SolidDatePickerDemo, {});
    case "searchfield":
      return h(SolidSearchFieldDemo, {});
    case "tooltip":
      return h(SolidTooltipDemo, {});
    case "toolbar":
      return h(SolidToolbarDemo, {});
    case "toast":
      return h(SolidToastDemo, {});
    default:
      return emptyState("No styled Solid demo is wired for this component yet.");
  }
}

function SolidDialogDemo() {
  const [isOpen, setIsOpen] = createSignal(false);
  const [focusReturned, setFocusReturned] = createSignal(false);
  const updateOpen = (open: boolean) => {
    setIsOpen(open);
    if (open) {
      setFocusReturned(false);
    }
  };

  return hc(
    "div",
    {
      class: `${comparisonSpectrumSkin.rootClass} comparison-stack`,
      get "data-comparison-open"() {
        return String(isOpen());
      },
      get "data-comparison-focus-returned"() {
        return String(focusReturned());
      },
    },
    [
      hc(
        HeadlessDialogTrigger,
        {
          onOpenChange: updateOpen,
        },
        [
          hc(
            SilapseButton,
            {
              variant: "primary",
              buttonStyle: "outline",
              class: `${comparisonSpectrumSkin.buttonClass} comparison-spectrum-Button--trigger`,
              "data-variant": "primary",
              "data-style": "outline",
              onFocus: () => {
                if (!isOpen()) {
                  setFocusReturned(true);
                }
              },
            },
            [h("span", { class: comparisonSpectrumSkin.labelClass, "data-slot": "label" }, "Open Dialog")],
          ),
          hc(
            HeadlessModalOverlay,
            {
              isDismissable: true,
              class: "comparison-dialog-underlay",
            },
            [
              hc(
                "div",
                { class: "comparison-dialog-positioner" },
                [
                  hc(
                    HeadlessModal,
                    { class: "comparison-dialog-modal" },
                    [
                      hc(
                        Dialog,
                        {
                          title: "Review Changes",
                          isDismissable: true,
                          class: `comparison-dialog-surface ${comparisonSpectrumSkin.dialogClass}`,
                        },
                        ["Dialog focus and dismissal are compared from this island."],
                      ),
                    ],
                  ),
                ],
              ),
            ],
          ),
        ],
      ),
    ],
  );
}

function SolidDatePickerDemo() {
  let root: HTMLDivElement | undefined;
  const [value, setValue] = createSignal("");
  const [open, setOpen] = createSignal(false);

  onMount(() => {
    const updateOpen = () => {
      setOpen(root?.querySelector("[data-open]") != null);
    };

    updateOpen();
    const observer = new MutationObserver(updateOpen);
    if (root) {
      observer.observe(root, {
        attributes: true,
        childList: true,
        subtree: true,
      });
    }
    onCleanup(() => observer.disconnect());
  });

  return hc(
    "div",
    {
      class: "comparison-spectrum-skin comparison-stack",
      ref: (element: HTMLDivElement) => {
        root = element;
      },
      get "data-comparison-value"() {
        return value();
      },
      get "data-comparison-open"() {
        return String(open());
      },
    },
    [
      hc(
        HeadlessDatePicker,
        {
          class: "comparison-form-control comparison-datepicker-root",
          "aria-label": "Due date",
          onChange: (nextValue: unknown) => {
            setValue(nextValue == null ? "" : String(nextValue));
          },
        },
        [
          hc(
            HeadlessDatePickerLabel,
            { class: "comparison-spectrum-Field-label", "data-slot": "label" },
            ["Due date"],
          ),
          hc(
            "div",
            { class: "comparison-datepicker-group" },
            [
              hc(
                HeadlessDateInput,
                {
                  class: "comparison-date-input",
                  children: renderProp((segment: unknown) => h(HeadlessDateSegment, { segment })),
                },
              ),
              hc(
                HeadlessDatePickerButton,
                {
                  class: "comparison-field-button",
                  "aria-label": "Calendar",
                },
                [hCalendarIcon()],
              ),
            ],
          ),
          hc(
            HeadlessDatePickerContent,
            { class: "comparison-popover comparison-datepicker-popover" },
            [
              hc(
                "div",
                { class: "comparison-popover-dialog" },
                [
                  hc(
                    HeadlessCalendar,
                    {},
                    [
                      hc(
                        "header",
                        { class: "comparison-datepicker-header" },
                        [
                          hc(
                            HeadlessCalendarButton,
                            {
                              slot: "previous",
                              class: "comparison-rac-button comparison-calendar-nav-button",
                              "aria-label": "Previous",
                            },
                            [hChevronIcon("left")],
                          ),
                          hc(HeadlessCalendarHeading, { class: "comparison-popover-title" }),
                          hc(
                            HeadlessCalendarButton,
                            {
                              slot: "next",
                              class: "comparison-rac-button comparison-calendar-nav-button",
                              "aria-label": "Next",
                            },
                            [hChevronIcon("right")],
                          ),
                        ],
                      ),
                      hc(
                        HeadlessCalendarGrid,
                        {
                          children: renderProp((date: unknown) => h(HeadlessCalendarCell, { date })),
                        },
                      ),
                    ],
                  ),
                ],
              ),
            ],
          ),
        ],
      ),
    ],
  );
}

function hCalendarIcon() {
  return h(
    "svg",
    {
      "aria-hidden": "true",
      fill: "none",
      focusable: "false",
      viewBox: "0 0 18 18",
    },
    [
      h("path", {
        d: "M5 2.25v2.5M13 2.25v2.5M3.25 6.75h11.5M4 3.75h10A1.25 1.25 0 0 1 15.25 5v9A1.25 1.25 0 0 1 14 15.25H4A1.25 1.25 0 0 1 2.75 14V5A1.25 1.25 0 0 1 4 3.75Z",
        stroke: "currentColor",
        "stroke-linecap": "round",
        "stroke-linejoin": "round",
        "stroke-width": "1.5",
      }),
    ],
  );
}

function hChevronIcon(direction: "left" | "right") {
  const path = direction === "left" ? "M11.25 3.75 6 9l5.25 5.25" : "M6.75 3.75 12 9l-5.25 5.25";

  return h(
    "svg",
    {
      "aria-hidden": "true",
      fill: "none",
      focusable: "false",
      viewBox: "0 0 18 18",
    },
    [
      h("path", {
        d: path,
        stroke: "currentColor",
        "stroke-linecap": "round",
        "stroke-linejoin": "round",
        "stroke-width": "1.75",
      }),
    ],
  );
}

function SolidSearchFieldDemo() {
  const [value, setValue] = createSignal("status");
  const [clearCount, setClearCount] = createSignal(0);

  return hc(
    "div",
    {
      class: "comparison-stack",
      get "data-comparison-input-value"() {
        return value();
      },
      get "data-comparison-clear-count"() {
        return String(clearCount());
      },
    },
    [
      hc(SearchField, {
        label: "Search",
        defaultValue: "status",
        onChange: setValue,
        onInput: (event: InputEvent) => {
          setValue((event.currentTarget as HTMLInputElement).value);
        },
        onClear: () => {
          setValue("");
          setClearCount((count) => count + 1);
        },
      }),
    ],
  );
}

function SolidTooltipDemo() {
  const [isOpen, setIsOpen] = createSignal(false);
  const [focusReturned, setFocusReturned] = createSignal(false);

  return hc(
    "div",
    {
      class: "comparison-stack",
      get "data-comparison-open"() {
        return String(isOpen());
      },
      get "data-comparison-focus-returned"() {
        return String(focusReturned());
      },
    },
    [
      hc(
        TooltipTrigger,
        {
          delay: 0,
          onOpenChange: (open: boolean) => setIsOpen(open),
        },
        [
          hc(
            SilapseButton,
            {
              variant: "secondary",
              onFocus: () => setFocusReturned(false),
              onBlur: () => setFocusReturned(true),
            },
            ["Inspect"],
          ),
          hc(Tooltip, {}, ["Tooltip content"]),
        ],
      ),
    ],
  );
}

function SolidToolbarDemo() {
  const [boldPressed, setBoldPressed] = createSignal(false);
  const [actionCount, setActionCount] = createSignal(0);

  return hc(
    "div",
    {
      class: "comparison-stack",
      get "data-comparison-pressed"() {
        return String(boldPressed());
      },
      get "data-comparison-action-count"() {
        return String(actionCount());
      },
    },
    [
      hc(
        Toolbar,
        { "aria-label": "Formatting tools" },
        renderProp(() => [
          hc(
            ToggleButton,
            {
              "aria-label": "Bold",
              get isSelected() {
                return boldPressed();
              },
              onChange: (pressed: boolean) => {
                setBoldPressed(pressed);
                setActionCount((count) => count + 1);
              },
            },
            ["Bold"],
          ),
          hc(
            SilapseButton,
            {
              variant: "secondary",
              buttonStyle: "outline",
              onPress: (_event: unknown) => setActionCount((count) => count + 1),
            },
            ["Italic"],
          ),
        ]),
      ),
    ],
  );
}

function SolidToastDemo() {
  const [visibleCount, setVisibleCount] = createSignal(0);
  const [shownCount, setShownCount] = createSignal(0);
  const toastKeys: string[] = [];

  const clearToasts = () => {
    for (const key of toastKeys.splice(0)) {
      globalToastQueue.close(key);
      globalToastQueue.remove(key);
    }
  };

  onMount(() => {
    const unsubscribe = globalToastQueue.subscribe((toasts) => {
      setVisibleCount(toasts.length);
    });
    onCleanup(unsubscribe);
  });
  onCleanup(clearToasts);

  const showToast = () => {
    const count = shownCount() + 1;
    setShownCount(count);
    const key = addToast({
      title: `Saved successfully ${count}`,
      description: "Toast region renders inside the comparison island.",
      type: "success",
    }, { timeout: 0 });
    toastKeys.push(key);
  };

  const toastRegion = createMemo(() => (
    visibleCount() > 0
      ? hc(
        ToastProvider,
        { useGlobalQueue: true },
        [hc(ToastRegion, { portal: false, placement: "bottom-start" })],
      )
      : null
  ));

  return hc(
    "div",
    {
      class: "comparison-stack",
      get "data-comparison-queued-count"() {
        return String(shownCount());
      },
      get "data-comparison-visible-count"() {
        return String(visibleCount());
      },
    },
    [
      hc("button", { type: "button", class: "comparison-rac-button", onClick: showToast }, ["Show toast"]),
      toastRegion,
    ],
  );
}

function SolidariaSpectrumButtonDemo() {
  const [actionCount, setActionCount] = createSignal(0);

  return hc(
    "div",
    {
      class: comparisonSpectrumSkin.rootClass,
      get "data-comparison-action-count"() {
        return String(actionCount());
      },
    },
    [hc(
      "div",
      { class: "comparison-button-row" },
      [
        hSpectrumButton({
          variant: "primary",
          style: "outline",
          onClick: (_event: MouseEvent) => setActionCount((count) => count + 1),
        }, "Primary"),
        hSpectrumButton({ variant: "accent", style: "fill" }, "Accent"),
        hSpectrumButton({ variant: "secondary", style: "outline" }, "Secondary"),
      ],
    )],
  );
}

function hSpectrumButton(
  props: {
    isDisabled?: boolean;
    variant: "primary" | "accent" | "secondary";
    style: "fill" | "outline";
    onClick?: (event: MouseEvent) => void;
    onFocus?: () => void;
  },
  label: string,
) {
  return hc(
    HeadlessButton,
    {
      isDisabled: props.isDisabled,
      class: comparisonSpectrumSkin.buttonClass,
      "data-variant": props.variant,
      "data-style": props.style,
      onClick: props.onClick,
      onFocus: props.onFocus,
    },
    [h("span", { class: comparisonSpectrumSkin.labelClass, "data-slot": "label" }, label)],
  );
}

function SolidariaSpectrumTextFieldDemo() {
  const [value, setValue] = createSignal("Quarterly report");

  return hc(
    "div",
    {
      class: comparisonSpectrumSkin.rootClass,
      get "data-comparison-value"() {
        return value();
      },
    },
    [hc(
      HeadlessTextField,
      {
        class: comparisonSpectrumSkin.fieldRootClass,
        defaultValue: "Quarterly report",
        "aria-label": "Name",
        "data-size": "medium",
        "data-variant": "default",
      },
      [
        h(
          HeadlessLabel,
          {
            for: "solidaria-spectrum-textfield-name",
            class: comparisonSpectrumSkin.fieldLabelClass,
            "data-slot": "label",
          },
          "Name",
        ),
        h(HeadlessInput, {
          id: "solidaria-spectrum-textfield-name",
          class: comparisonSpectrumSkin.fieldInputClass,
          "data-slot": "input",
          onInput: (event: InputEvent) => {
            setValue((event.currentTarget as HTMLInputElement).value);
          },
        }),
      ],
    )],
  );
}

function SolidariaSpectrumSelectDemo() {
  const [selectedKey, setSelectedKey] = createSignal<string | null>("bravo");

  return hc(
    "div",
    {
      class: comparisonSpectrumSkin.rootClass,
      get "data-comparison-selected-key"() {
        return selectedKey() ?? "";
      },
    },
    [hc(
      HeadlessSelect,
      {
        class: comparisonSpectrumSkin.selectRootClass,
        items: selectItems,
        defaultSelectedKey: "bravo",
        onSelectionChange: (key: string | number | null) => {
          setSelectedKey(key == null ? null : String(key));
        },
        getKey: (item: (typeof selectItems)[number]) => item.id,
        getTextValue: (item: (typeof selectItems)[number]) => item.label,
        "data-size": "medium",
        "data-variant": "default",
      },
      [
        hc(
          HeadlessLabel,
          {
            class: comparisonSpectrumSkin.fieldLabelClass,
            "data-slot": "label",
          },
          ["Channel"],
        ),
        hc(
          HeadlessSelectTrigger,
          { class: comparisonSpectrumSkin.selectTriggerClass },
          [h(HeadlessSelectValue, {
            class: comparisonSpectrumSkin.selectValueClass,
            "data-slot": "value",
          })],
        ),
        hc(
          HeadlessSelectListBox,
          { class: comparisonSpectrumSkin.selectListBoxClass },
          renderProp((item: (typeof selectItems)[number]) =>
            h(
              HeadlessSelectOption,
              {
                id: item.id,
                class: comparisonSpectrumSkin.selectOptionClass,
              },
              item.label,
            )),
        ),
      ],
    )],
  );
}

function SolidCheckboxDemo() {
  const [checked, setChecked] = createSignal(true);

  return hc(
    "div",
    {
      class: "comparison-stack",
      get "data-comparison-checked"() {
        return String(checked());
      },
    },
    [
      hc(
        Checkbox,
        {
          defaultSelected: true,
          onChange: setChecked,
        },
        ["Enable alerts"],
      ),
    ],
  );
}

function SolidRadioDemo() {
  const [selectedKey, setSelectedKey] = createSignal("compact");

  return hc(
    "div",
    {
      class: "comparison-stack",
      get "data-comparison-selected-key"() {
        return selectedKey();
      },
    },
    [
      hc(
        RadioGroup,
        {
          label: "Density",
          defaultValue: "compact",
          onChange: setSelectedKey,
        },
        renderProp(() => [
          hc(Radio, { value: "compact" }, ["Compact"]),
          hc(Radio, { value: "comfortable" }, ["Comfortable"]),
        ]),
      ),
    ],
  );
}

function renderComponents(componentSlug: ComparisonSlug) {
  switch (componentSlug) {
    case "button":
      return h(
        "div",
        { class: "comparison-stack" },
        h(HeadlessButton, { class: "comparison-rac-button" }, "Component Button"),
        h(
          HeadlessButton,
          {
            isDisabled: true,
            class: "comparison-rac-button comparison-rac-button--muted",
          },
          "Disabled by props",
        ),
      );
    case "popover":
      return h(
        "div",
        { class: "comparison-stack" },
        h(
          HeadlessPopoverTrigger,
          {},
          h(HeadlessButton, { class: "comparison-rac-button" }, "Open Popover"),
          h(
            HeadlessPopover,
            {
              class: "comparison-popover",
              "aria-label": "Quick audit note",
            },
            h(
              "div",
              { class: "comparison-popover-dialog" },
              h(
                "div",
                { class: "comparison-popover-title" },
                "Confirm Action",
              ),
              h(
                "p",
                {},
                "Outside press and escape should dismiss this overlay without escaping its local comparison root.",
              ),
            ),
          ),
        ),
      );
    case "tabs":
      return h(
        HeadlessTabs,
        {
          class: "comparison-rac-tabs",
          "aria-label": "solidaria-components tabs",
          items: tabItems,
          getKey: (item: TabItem) => item.id,
          getTextValue: (item: TabItem) => item.label,
        },
        h(
          HeadlessTabList,
          { class: "comparison-rac-tab-list" },
          (item: TabItem) =>
            h(
              HeadlessTab,
              { id: item.id, class: "comparison-rac-tab" },
              item.label,
            ),
        ),
        h(
          HeadlessTabPanels,
          { class: "comparison-tab-panels" },
          tabItems.map((item) =>
            h(
              HeadlessTabPanel,
              { id: item.id, class: "comparison-tabs-panel" },
              item.content,
            ),
          ),
        ),
      );
    default:
      return emptyState(
        "No component-layer Solid demo is wired for this component yet.",
      );
  }
}

function renderHeadless(componentSlug: ComparisonSlug) {
  switch (componentSlug) {
    case "button":
      return h(SolidHeadlessButtonDemo, {});
    default:
      return emptyState("No headless Solid demo is wired for this component yet.");
  }
}

function SolidHeadlessButtonDemo() {
  const [pressCount, setPressCount] = createSignal(0);
  const button = createButton({
    onPress: () => setPressCount((count) => count + 1),
    "aria-label": "Headless action",
  });

  return h(
    "div",
    { class: "comparison-headless-stack" },
    h(
      "button",
      {
        ...button.buttonProps,
        type: "button",
        class: "comparison-headless-button",
      },
      () => (button.isPressed() ? "Pressed" : `Pressed ${pressCount()} times`),
    ),
    h(
      "p",
      { class: "comparison-helper-copy" },
      "This uses the raw `createButton` primitive rather than a pre-wired component.",
    ),
  );
}

function emptyState(message: string) {
  return h("div", { class: "comparison-empty-state" }, message);
}

const providerShellStyle = {
  padding: "20px",
  "border-radius": "18px",
  background:
    "linear-gradient(180deg, rgba(7, 14, 22, 0.92), rgba(8, 22, 38, 0.78))",
};

const nestedProviderStyle = {
  padding: "16px",
  margin: "16px 0 0",
  "border-radius": "16px",
};
