// apps/comparison/src/components/react/fixtures/styled.jsx
import { jsx, jsxs } from "react/jsx-runtime";
import { useEffect, useState } from "react";
import {
  ActionButton as SpectrumActionButton,
  ActionButtonGroup as SpectrumActionButtonGroup,
  Button as SpectrumButton,
  ButtonGroup as SpectrumButtonGroup,
  Card as SpectrumCard,
  CardView as SpectrumCardView,
  Checkbox as SpectrumCheckbox,
  Content as SpectrumContent,
  DatePicker as SpectrumDatePicker,
  Dialog as SpectrumDialog,
  DialogTrigger as SpectrumDialogTrigger,
  Heading as SpectrumHeading,
  LinkButton as SpectrumLinkButton,
  Provider as SpectrumProvider,
  SearchField as SpectrumSearchField,
  SegmentedControl as SpectrumSegmentedControl,
  SegmentedControlItem as SpectrumSegmentedControlItem,
  SelectBox as SpectrumSelectBox,
  SelectBoxGroup as SpectrumSelectBoxGroup,
  Tab as SpectrumTab,
  TabList as SpectrumTabList,
  TabPanel as SpectrumTabPanel,
  Tabs as SpectrumTabs,
  Text as SpectrumText,
  TextField as SpectrumTextField,
  Tooltip as SpectrumTooltip,
  TooltipTrigger as SpectrumTooltipTrigger,
  ToggleButton as SpectrumToggleButton,
  ToggleButtonGroup as SpectrumToggleButtonGroup,
  createIcon,
} from "@react-spectrum/s2";
import "@react-spectrum/s2/page.css";
import {
  actionButtonDemoPropsFromWindow,
  comparisonControlsEvent as actionButtonControlsEvent,
  serializeActionButtonDemoProps,
} from "@comparison/data/actionbutton-demo";
import {
  comparisonActionItems as actionItems,
  comparisonTabItems as tabItems,
} from "@comparison/data/comparison-contract";
import {
  buttonDemoPropsFromWindow,
  comparisonControlsEvent,
  serializeButtonDemoProps,
} from "@comparison/data/button-demo";
import {
  comparisonThemeChangeEvent,
  getComparisonResolvedThemeFromDocument,
} from "@comparison/data/theme";

const ReactButtonIcon = createIcon((props) =>
  jsxs("svg", {
    xmlns: "http://www.w3.org/2000/svg",
    width: "20",
    height: "20",
    viewBox: "0 0 20 20",
    ...props,
    children: [
      jsx("path", {
        d: "m18,4.25v11.5c0,1.24072-1.00928,2.25-2.25,2.25H4.25c-1.24072,0-2.25-1.00928-2.25-2.25V4.25c0-1.24072,1.00928-2.25,2.25-2.25h11.5c1.24072,0,2.25,1.00928,2.25,2.25Zm-1.5,0c0-.41357-.33643-.75-.75-.75H4.25c-.41357,0-.75.33643-.75.75v11.5c0,.41357.33643.75.75.75h11.5c.41357,0,.75-.33643.75-.75V4.25Z",
        fill: "var(--iconPrimary, #222)",
      }),
      jsx("path", {
        d: "m13.76318,10c0,.42139-.3418.76318-.76318.76318h-2.23682v2.23682c0,.42139-.3418.76318-.76318.76318s-.76318-.3418-.76318-.76318v-2.23682h-2.23682c-.42139,0-.76318-.3418-.76318-.76318s.3418-.76318.76318-.76318h2.23682v-2.23682c0-.42139.3418-.76318.76318-.76318s.76318.3418.76318.76318v2.23682h2.23682c.42139,0,.76318.3418.76318.76318Z",
        fill: "var(--iconPrimary, #222)",
      }),
    ],
  }),
);

const selectBoxItems = [
  { id: "starter", label: "Starter", description: "For small teams" },
  { id: "pro", label: "Pro", description: "For growing teams" },
];

const cardItems = [
  { id: "apollo", title: "Apollo", status: "Active" },
  { id: "zephyr", title: "Zephyr", status: "Queued" },
];

function booleanParamFromWindow(name) {
  if (typeof window === "undefined") {
    return false;
  }

  const value = new URLSearchParams(window.location.search).get(name);
  return value === "true" || value === "on" || value === "1";
}

function iconPlacementFromWindow() {
  if (typeof window === "undefined") {
    return "none";
  }

  const value = new URLSearchParams(window.location.search).get("iconPlacement");
  return value === "start" || value === "only" ? value : "none";
}

export const reactStyledFixtures = {
  provider: renderProviderDemo,
  button: () => jsx(ReactButtonDemo, {}),
  actionbutton: () => jsx(ReactActionButtonDemo, {}),
  actionbuttongroup: () => jsx(ReactActionButtonGroupDemo, {}),
  buttongroup: () => jsx(ReactButtonGroupDemo, {}),
  linkbutton: () => jsx(ReactLinkButtonDemo, {}),
  togglebutton: () => jsx(ReactToggleButtonDemo, {}),
  togglebuttongroup: () => jsx(ReactToggleButtonGroupDemo, {}),
  tabs: renderTabsDemo,
  textfield: () => jsx(ReactTextFieldDemo, {}),
  checkbox: () => jsx(ReactCheckboxDemo, {}),
  dialog: () => jsx(ReactDialogDemo, {}),
  datepicker: () => jsx(ReactDatePickerDemo, {}),
  searchfield: () => jsx(ReactSearchFieldDemo, {}),
  cardview: () => jsx(ReactCardViewDemo, {}),
  segmentedcontrol: () => jsx(ReactSegmentedControlDemo, {}),
  selectboxgroup: () => jsx(ReactSelectBoxGroupDemo, {}),
  tooltip: renderTooltipDemo,
  toast: renderToastGap,
};

function renderProviderDemo() {
  return jsx(SpectrumProvider, {
    colorScheme: "dark",
    background: "base",
    UNSAFE_style: providerShellStyle,
    children: jsxs("div", {
      className: "comparison-provider-stack",
      children: [
        jsx("div", {
          className: "comparison-provider-caption",
          children: "Outer provider: dark / medium scale",
        }),
        jsx(SpectrumButton, {
          variant: "primary",
          children: "Inherited Action",
        }),
        jsxs(SpectrumProvider, {
          colorScheme: "light",
          background: "base",
          UNSAFE_style: nestedProviderStyle,
          children: [
            jsx("div", {
              className: "comparison-provider-caption",
              children: "Nested provider: local light override",
            }),
            jsx(SpectrumButton, {
              variant: "accent",
              children: "Nested Override",
            }),
          ],
        }),
      ],
    }),
  });
}

function renderReactSpectrumReference(children, colorScheme = "dark") {
  return jsx(SpectrumProvider, {
    colorScheme,
    background: "base",
    UNSAFE_style: providerShellStyle,
    children,
  });
}

function ReactButtonDemo() {
  const [actionCount, setActionCount] = useState(0);
  const demoProps = useButtonDemoControls();
  const colorScheme = useComparisonResolvedTheme();
  return renderReactSpectrumReference(
    jsx("div", {
      "data-comparison-action-count": String(actionCount),
      "data-comparison-button-props": serializeButtonDemoProps(demoProps),
      children: jsx("div", {
        className: "comparison-button-row",
        children: jsx(SpectrumButton, {
          variant: demoProps.variant,
          fillStyle: demoProps.fillStyle,
          size: demoProps.size,
          staticColor: demoProps.staticColor,
          isDisabled: demoProps.isDisabled,
          isPending: demoProps.isPending,
          "aria-label": demoProps.iconPlacement === "only" ? demoProps.children : void 0,
          onPress: () => setActionCount((count) => count + 1),
          children: renderButtonChildren(demoProps),
        }),
      }),
    }),
    colorScheme,
  );
}

function renderButtonChildren(demoProps) {
  if (demoProps.iconPlacement === "start") {
    return [
      jsx(ReactButtonIcon, {}, "icon"),
      jsx(SpectrumText, { children: demoProps.children }, "text"),
    ];
  }

  if (demoProps.iconPlacement === "end") {
    return [
      jsx(SpectrumText, { children: demoProps.children }, "text"),
      jsx(ReactButtonIcon, {}, "icon"),
    ];
  }

  if (demoProps.iconPlacement === "only") {
    return jsx(ReactButtonIcon, {});
  }

  return demoProps.children;
}

function renderSingleButtonFamilyChildren(label, iconPlacement) {
  if (iconPlacement === "start") {
    return [jsx(ReactButtonIcon, {}, "icon"), jsx(SpectrumText, { children: label }, "text")];
  }

  if (iconPlacement === "only") {
    return jsx(ReactButtonIcon, {});
  }

  return label;
}

function useComparisonResolvedTheme() {
  const [colorScheme, setColorScheme] = useState(getComparisonResolvedThemeFromDocument);
  useEffect(() => {
    const handleThemeChange = (event) => {
      if (event instanceof CustomEvent && event.detail?.resolvedTheme) {
        setColorScheme(event.detail.resolvedTheme);
      }
    };
    window.addEventListener(comparisonThemeChangeEvent, handleThemeChange);
    setColorScheme(getComparisonResolvedThemeFromDocument());
    return () => window.removeEventListener(comparisonThemeChangeEvent, handleThemeChange);
  }, []);
  return colorScheme;
}

function useButtonDemoControls() {
  const [demoProps, setDemoProps] = useState(buttonDemoPropsFromWindow);
  useEffect(() => {
    const handleControlsChange = (event) => {
      if (event instanceof CustomEvent && event.detail?.component === "button") {
        setDemoProps(event.detail.props);
      }
    };
    window.addEventListener(comparisonControlsEvent, handleControlsChange);
    return () => window.removeEventListener(comparisonControlsEvent, handleControlsChange);
  }, []);
  return demoProps;
}

function ReactActionButtonDemo() {
  const [actionCount, setActionCount] = useState(0);
  const demoProps = useActionButtonDemoControls();
  const colorScheme = useComparisonResolvedTheme();
  return renderReactSpectrumReference(
    jsx("div", {
      className: "comparison-button-row",
      "data-comparison-action-count": String(actionCount),
      "data-comparison-actionbutton-props": serializeActionButtonDemoProps(demoProps),
      "data-comparison-actionbutton-pending": demoProps.isPending ? "true" : void 0,
      children: jsx(SpectrumActionButton, {
        size: demoProps.size,
        staticColor: demoProps.staticColor,
        isQuiet: demoProps.isQuiet,
        isDisabled: demoProps.isDisabled,
        isPending: demoProps.isPending,
        "aria-label": demoProps.iconPlacement === "only" ? demoProps.children : void 0,
        onPress: () => setActionCount((count) => count + 1),
        children: renderSingleButtonFamilyChildren(demoProps.children, demoProps.iconPlacement),
      }),
    }),
    colorScheme,
  );
}

function useActionButtonDemoControls() {
  const [demoProps, setDemoProps] = useState(actionButtonDemoPropsFromWindow);
  useEffect(() => {
    const handleControlsChange = (event) => {
      if (event instanceof CustomEvent && event.detail?.component === "actionbutton") {
        setDemoProps(event.detail.props);
      }
    };
    window.addEventListener(actionButtonControlsEvent, handleControlsChange);
    return () => window.removeEventListener(actionButtonControlsEvent, handleControlsChange);
  }, []);
  return demoProps;
}

function ReactActionButtonGroupDemo() {
  const [selectedKeys, setSelectedKeys] = useState(() => new Set(["bold"]));
  const [actionKey, setActionKey] = useState("");
  const selectedKeyText = Array.from(selectedKeys).join(",");
  const toggleKey = (key) => {
    setActionKey(key);
    setSelectedKeys(new Set([key]));
  };
  return renderReactSpectrumReference(
    jsx("div", {
      "data-comparison-action-key": actionKey,
      "data-comparison-selected-keys": selectedKeyText,
      children: jsx(SpectrumActionButtonGroup, {
        "aria-label": "Formatting actions",
        children: actionItems.map((item) =>
          jsx(
            SpectrumActionButton,
            {
              "aria-pressed": selectedKeys.has(item.id),
              onPress: () => toggleKey(item.id),
              children: item.label,
            },
            item.id,
          ),
        ),
      }),
    }),
  );
}

function ReactButtonGroupDemo() {
  const [actionKey, setActionKey] = useState("");
  return renderReactSpectrumReference(
    jsx("div", {
      "data-comparison-action-key": actionKey,
      children: jsxs(SpectrumButtonGroup, {
        children: [
          jsx(SpectrumButton, {
            variant: "primary",
            onPress: () => setActionKey("save"),
            children: "Save",
          }),
          jsx(SpectrumButton, {
            variant: "secondary",
            onPress: () => setActionKey("cancel"),
            children: "Cancel",
          }),
        ],
      }),
    }),
  );
}

function ReactLinkButtonDemo() {
  const colorScheme = useComparisonResolvedTheme();
  const iconPlacement = iconPlacementFromWindow();
  return renderReactSpectrumReference(
    jsx("div", {
      className: "comparison-button-row",
      children: jsx(SpectrumLinkButton, {
        href: "https://example.com/docs",
        variant: "primary",
        fillStyle: "fill",
        "aria-label": iconPlacement === "only" ? "Open docs" : void 0,
        children: renderSingleButtonFamilyChildren("Open docs", iconPlacement),
      }),
    }),
    colorScheme,
  );
}

function ReactToggleButtonDemo() {
  const iconPlacement = iconPlacementFromWindow();
  const [selected, setSelected] = useState(() => booleanParamFromWindow("isSelected"));
  return renderReactSpectrumReference(
    jsx("div", {
      "data-comparison-selected": String(selected),
      children: jsx(SpectrumToggleButton, {
        isSelected: selected,
        onChange: setSelected,
        "aria-label": iconPlacement === "only" ? "Pin" : void 0,
        children: renderSingleButtonFamilyChildren("Pin", iconPlacement),
      }),
    }),
  );
}

function ReactToggleButtonGroupDemo() {
  const [selectedKeys, setSelectedKeys] = useState(() => new Set(["left"]));
  const colorScheme = useComparisonResolvedTheme();
  return renderReactSpectrumReference(
    jsx("div", {
      "data-comparison-selected-keys": Array.from(selectedKeys).join(","),
      children: jsxs(SpectrumToggleButtonGroup, {
        "aria-label": "Text alignment",
        selectionMode: "single",
        selectedKeys,
        onSelectionChange: setSelectedKeys,
        children: [
          jsx(SpectrumToggleButton, { id: "left", children: "Left" }),
          jsx(SpectrumToggleButton, { id: "center", children: "Center" }),
          jsx(SpectrumToggleButton, { id: "right", children: "Right" }),
        ],
      }),
    }),
    colorScheme,
  );
}

function ReactSegmentedControlDemo() {
  const [selectedKey, setSelectedKey] = useState("list");
  const colorScheme = useComparisonResolvedTheme();
  return renderReactSpectrumReference(
    jsx("div", {
      "data-comparison-selected-key": selectedKey,
      children: jsxs(SpectrumSegmentedControl, {
        "aria-label": "View mode",
        selectedKey,
        onSelectionChange: (key) => setSelectedKey(String(key)),
        children: [
          jsx(SpectrumSegmentedControlItem, { id: "list", children: "List" }),
          jsx(SpectrumSegmentedControlItem, { id: "grid", children: "Grid" }),
          jsx(SpectrumSegmentedControlItem, { id: "board", children: "Board" }),
        ],
      }),
    }),
    colorScheme,
  );
}

function ReactSelectBoxGroupDemo() {
  const [selectedKeys, setSelectedKeys] = useState(() => new Set(["starter"]));
  const colorScheme = useComparisonResolvedTheme();
  return renderReactSpectrumReference(
    jsx("div", {
      "data-comparison-selected-keys": Array.from(selectedKeys).join(","),
      children: jsx(SpectrumSelectBoxGroup, {
        "aria-label": "Plans",
        orientation: "horizontal",
        selectedKeys,
        onSelectionChange: (keys) => setSelectedKeys(keys === "all" ? new Set() : new Set(keys)),
        children: selectBoxItems.map((item) =>
          jsxs(
            SpectrumSelectBox,
            {
              id: item.id,
              textValue: item.label,
              children: [
                jsx(SpectrumText, { slot: "label", children: item.label }),
                jsx(SpectrumText, { slot: "description", children: item.description }),
              ],
            },
            item.id,
          ),
        ),
      }),
    }),
    colorScheme,
  );
}

function ReactCardViewDemo() {
  const [selectedKeys, setSelectedKeys] = useState(() => new Set(["apollo"]));
  const colorScheme = useComparisonResolvedTheme();
  return renderReactSpectrumReference(
    jsx("div", {
      "data-comparison-selected-keys": Array.from(selectedKeys).join(","),
      children: jsx(SpectrumCardView, {
        "aria-label": "Projects",
        items: cardItems,
        size: "S",
        density: "compact",
        variant: "secondary",
        selectionMode: "single",
        selectionStyle: "highlight",
        UNSAFE_style: cardViewDemoStyle,
        selectedKeys,
        onSelectionChange: (keys) => setSelectedKeys(keys === "all" ? new Set() : new Set(keys)),
        children: (item) =>
          jsxs(SpectrumCard, {
            id: item.id,
            textValue: item.title,
            children: [
              jsx(SpectrumText, { slot: "title", children: item.title }),
              jsx(SpectrumText, { slot: "description", children: item.status }),
            ],
          }),
      }),
    }),
    colorScheme,
  );
}

function renderTabsDemo() {
  return renderReactSpectrumReference(
    jsxs(SpectrumTabs, {
      "aria-label": "React Spectrum tabs",
      children: [
        jsx(SpectrumTabList, {
          items: tabItems,
          children: (item) => jsx(SpectrumTab, { id: item.id, children: item.label }),
        }),
        tabItems.map((item) =>
          jsx(SpectrumTabPanel, { id: item.id, children: item.content }, item.id),
        ),
      ],
    }),
  );
}

function ReactTextFieldDemo() {
  const [value, setValue] = useState("Quarterly report");
  return renderReactSpectrumReference(
    jsx("div", {
      "data-comparison-value": value,
      children: jsx(SpectrumTextField, {
        label: "Name",
        defaultValue: "Quarterly report",
        onChange: setValue,
      }),
    }),
  );
}

function ReactDialogDemo() {
  const [isOpen, setIsOpen] = useState(false);
  return renderReactSpectrumReference(
    jsx("div", {
      "data-comparison-open": String(isOpen),
      children: jsxs(SpectrumDialogTrigger, {
        isDismissable: true,
        onOpenChange: setIsOpen,
        children: [
          jsx(SpectrumButton, { variant: "primary", children: "Open Dialog" }),
          jsxs(SpectrumDialog, {
            isDismissible: true,
            children: [
              jsx(SpectrumHeading, { slot: "title", children: "Review Changes" }),
              jsx(SpectrumContent, {
                children: jsx(SpectrumText, {
                  children: "Dialog focus and dismissal are compared from this island.",
                }),
              }),
            ],
          }),
        ],
      }),
    }),
  );
}

function ReactCheckboxDemo() {
  const [checked, setChecked] = useState(true);
  return renderReactSpectrumReference(
    jsx("div", {
      "data-comparison-checked": String(checked),
      children: jsx(SpectrumCheckbox, {
        defaultSelected: true,
        onChange: setChecked,
        children: "Enable alerts",
      }),
    }),
  );
}

function ReactDatePickerDemo() {
  const [value, setValue] = useState("");
  const [isOpen, setIsOpen] = useState(false);
  return renderReactSpectrumReference(
    jsx("div", {
      "data-comparison-value": value,
      "data-comparison-open": String(isOpen),
      children: jsx(SpectrumDatePicker, {
        label: "Due date",
        onChange: (nextValue) => setValue(nextValue == null ? "" : String(nextValue)),
        onOpenChange: setIsOpen,
        UNSAFE_className: "comparison-datepicker-root",
      }),
    }),
  );
}

function ReactSearchFieldDemo() {
  const [value, setValue] = useState("status");
  const [clearCount, setClearCount] = useState(0);
  return renderReactSpectrumReference(
    jsx("div", {
      "data-comparison-input-value": value,
      "data-comparison-clear-count": String(clearCount),
      children: jsx(SpectrumSearchField, {
        label: "Search",
        defaultValue: "status",
        onChange: setValue,
        onClear: () => {
          setValue("");
          setClearCount((count) => count + 1);
        },
      }),
    }),
  );
}

function renderTooltipDemo() {
  return renderReactSpectrumReference(
    jsxs(SpectrumTooltipTrigger, {
      delay: 0,
      children: [
        jsx(SpectrumActionButton, { children: "Inspect" }),
        jsx(SpectrumTooltip, { children: "Tooltip content" }),
      ],
    }),
  );
}

function renderToastGap() {
  return jsx("div", {
    className: "comparison-empty-state",
    children: "React Aria Components 1.15.1 does not expose Toast.",
  });
}

const providerShellStyle = {
  padding: 0,
  background: "transparent",
};

const cardViewDemoStyle = {
  width: 360,
  height: 180,
};

const nestedProviderStyle = {
  padding: 16,
  marginTop: 16,
  borderRadius: 16,
};

// apps/comparison/src/components/solid/fixtures/styled.tsx
import h from "solid-js/h";
import { createMemo, createSignal, onCleanup, onMount, type JSX } from "solid-js";
import { hc, renderProp } from "../solid-h";
import {
  ActionButton as SolidSpectrumActionButton,
  ActionButtonGroup as SolidSpectrumActionButtonGroup,
  Button as SolidSpectrumButton,
  ButtonGroup as SolidSpectrumButtonGroup,
  Card as SolidSpectrumCard,
  CardView as SolidSpectrumCardView,
  LinkButton as SolidSpectrumLinkButton,
  Provider as SolidSpectrumProvider,
  SegmentedControl as SolidSpectrumSegmentedControl,
  SegmentedControlItem as SolidSpectrumSegmentedControlItem,
  SelectBox as SolidSpectrumSelectBox,
  SelectBoxGroup as SolidSpectrumSelectBoxGroup,
  ToggleButton as SolidSpectrumToggleButton,
  ToggleButtonGroup as SolidSpectrumToggleButtonGroup,
  createIcon,
} from "@proyecto-viviana/solid-spectrum";
import { s2ButtonText } from "../../../../../../packages/solid-spectrum/src/button/s2-button-styles";
import {
  s2ActionButtonText,
  s2ToggleButtonText,
} from "../../../../../../packages/solid-spectrum/src/button/s2-action-button-styles";
import type { ComparisonSlug } from "@comparison/data/comparison-manifest";
import { comparisonActionItems as actionItems } from "@comparison/data/comparison-contract";
import {
  actionButtonDemoPropsFromWindow,
  serializeActionButtonDemoProps,
  type ActionButtonDemoProps,
} from "@comparison/data/actionbutton-demo";
import {
  buttonDemoPropsFromWindow,
  comparisonControlsEvent,
  serializeButtonDemoProps,
  type ButtonDemoProps,
} from "@comparison/data/button-demo";
import {
  comparisonThemeChangeEvent,
  getComparisonResolvedThemeFromDocument,
  type ComparisonResolvedTheme,
} from "@comparison/data/theme";

type ActionItem = (typeof actionItems)[number];
type SolidStyledFixture = () => ReturnType<typeof h>;

const SolidNewIcon = createIcon((props: JSX.SvgSVGAttributes<SVGSVGElement>) => {
  const { class: className, ...rest } = props;
  return h(
    "svg",
    {
      xmlns: "http://www.w3.org/2000/svg",
      width: "20",
      height: "20",
      viewBox: "0 0 20 20",
      ...rest,
      class: className,
    },
    h("path", {
      d: "m18,4.25v11.5c0,1.24072-1.00928,2.25-2.25,2.25H4.25c-1.24072,0-2.25-1.00928-2.25-2.25V4.25c0-1.24072,1.00928-2.25,2.25-2.25h11.5c1.24072,0,2.25,1.00928,2.25,2.25Zm-1.5,0c0-.41357-.33643-.75-.75-.75H4.25c-.41357,0-.75.33643-.75.75v11.5c0,.41357.33643.75.75.75h11.5c.41357,0,.75-.33643.75-.75V4.25Z",
      fill: "var(--iconPrimary, #222)",
    }),
    h("path", {
      d: "m13.76318,10c0,.42139-.3418.76318-.76318.76318h-2.23682v2.23682c0,.42139-.3418.76318-.76318.76318s-.76318-.3418-.76318-.76318v-2.23682h-2.23682c-.42139,0-.76318-.3418-.76318-.76318s.3418-.76318.76318-.76318h2.23682v-2.23682c0-.42139.3418-.76318.76318-.76318s.76318.3418.76318.76318v2.23682h2.23682c.42139,0,.76318.3418.76318.76318Z",
      fill: "var(--iconPrimary, #222)",
    }),
  )() as JSX.Element;
});

const selectBoxItems = [
  { id: "starter", label: "Starter", description: "For small teams" },
  { id: "pro", label: "Pro", description: "For growing teams" },
];

const cardItems = [
  { id: "apollo", title: "Apollo", status: "Active" },
  { id: "zephyr", title: "Zephyr", status: "Queued" },
];

type SingleButtonIconPlacement = "none" | "start" | "only";

function booleanParamFromWindow(name: string) {
  if (typeof window === "undefined") {
    return false;
  }

  const value = new URLSearchParams(window.location.search).get(name);
  return value === "true" || value === "on" || value === "1";
}

function iconPlacementFromWindow(): SingleButtonIconPlacement {
  if (typeof window === "undefined") {
    return "none";
  }

  const value = new URLSearchParams(window.location.search).get("iconPlacement");
  return value === "start" || value === "only" ? value : "none";
}

function solidSingleButtonFamilyChildren(
  label: string,
  iconPlacement: SingleButtonIconPlacement,
  textClass: () => string,
) {
  if (iconPlacement === "start") {
    return [
      () => h(SolidNewIcon, { "aria-hidden": "true" }),
      () => h("span", { class: textClass(), "data-rsp-slot": "text" }, label),
    ];
  }

  if (iconPlacement === "only") {
    return [() => h(SolidNewIcon, { "aria-hidden": "true" })];
  }

  return [() => h("span", { class: textClass(), "data-rsp-slot": "text" }, label)];
}

export const solidStyledFixtures: Partial<Record<ComparisonSlug, SolidStyledFixture>> = {
  provider: renderProviderDemo,
  button: () => h(SolidSpectrumButtonDemo, {}),
  actionbutton: () => h(SolidSpectrumActionButtonDemo, {}),
  actionbuttongroup: () => h(SolidSpectrumActionButtonGroupDemo, {}),
  buttongroup: () => h(SolidSpectrumButtonGroupDemo, {}),
  linkbutton: () => h(SolidSpectrumLinkButtonDemo, {}),
  cardview: () => h(SolidSpectrumCardViewDemo, {}),
  segmentedcontrol: () => h(SolidSpectrumSegmentedControlDemo, {}),
  selectboxgroup: () => h(SolidSpectrumSelectBoxGroupDemo, {}),
  togglebutton: () => h(SolidSpectrumToggleButtonDemo, {}),
  togglebuttongroup: () => h(SolidSpectrumToggleButtonGroupDemo, {}),
};

function renderProviderDemo() {
  return h(
    SolidSpectrumProvider,
    { colorScheme: "dark", background: "base", style: providerShellStyle },
    h(
      "div",
      { class: "comparison-provider-stack" },
      h("div", { class: "comparison-provider-caption" }, "Outer provider: dark / medium scale"),
      h(SolidSpectrumButton, { variant: "primary" }, "Inherited Action"),
      h(
        SolidSpectrumProvider,
        { colorScheme: "light", background: "base", style: nestedProviderStyle },
        h("div", { class: "comparison-provider-caption" }, "Nested provider: local light override"),
        h(SolidSpectrumButton, { variant: "accent" }, "Nested Override"),
      ),
    ),
  );
}

function SolidSpectrumButtonDemo() {
  const [actionCount, setActionCount] = createSignal(0);
  const [demoProps, setDemoProps] = createSignal(buttonDemoPropsFromWindow());
  const [colorScheme, setColorScheme] = createSignal<ComparisonResolvedTheme>(
    getComparisonResolvedThemeFromDocument(),
  );

  onMount(() => {
    const handleControlsChange = (event: Event) => {
      if (event instanceof CustomEvent && event.detail?.component === "button") {
        setDemoProps(event.detail.props as ButtonDemoProps);
      }
    };
    const handleThemeChange = (event: Event) => {
      if (event instanceof CustomEvent && event.detail?.resolvedTheme) {
        setColorScheme(event.detail.resolvedTheme as ComparisonResolvedTheme);
      }
    };
    window.addEventListener(comparisonControlsEvent, handleControlsChange);
    window.addEventListener(comparisonThemeChangeEvent, handleThemeChange);
    setColorScheme(getComparisonResolvedThemeFromDocument());
    onCleanup(() => {
      window.removeEventListener(comparisonControlsEvent, handleControlsChange);
      window.removeEventListener(comparisonThemeChangeEvent, handleThemeChange);
    });
  });

  const renderedButton = createMemo(() => {
    const props = demoProps();
    const children =
      props.iconPlacement === "start"
        ? [
            () => h(SolidNewIcon, { "aria-hidden": "true" }),
            () =>
              h(
                "span",
                {
                  class: s2ButtonText({ isProgressVisible: props.isPending }),
                  "data-rsp-slot": "text",
                },
                props.children,
              ),
          ]
        : props.iconPlacement === "end"
          ? [
              () =>
                h(
                  "span",
                  {
                    class: s2ButtonText({ isProgressVisible: props.isPending }),
                    "data-rsp-slot": "text",
                  },
                  props.children,
                ),
              () => h(SolidNewIcon, { "aria-hidden": "true" }),
            ]
          : props.iconPlacement === "only"
            ? [() => h(SolidNewIcon, { "aria-hidden": "true" })]
            : [
                () =>
                  h(
                    "span",
                    {
                      class: s2ButtonText({ isProgressVisible: props.isPending }),
                      "data-rsp-slot": "text",
                    },
                    props.children,
                  ),
              ];

    return hc(
      SolidSpectrumButton,
      {
        isDisabled: props.isDisabled,
        isPending: props.isPending,
        variant: props.variant,
        fillStyle: props.fillStyle,
        size: props.size,
        staticColor: props.staticColor,
        ...(props.iconPlacement === "only" ? { "aria-label": props.children } : {}),
        onPress: (_event: unknown) => {
          if (!props.isPending) {
            setActionCount((count) => count + 1);
          }
        },
      },
      children,
    );
  });

  return hc(
    SolidSpectrumProvider,
    {
      get colorScheme() {
        return colorScheme();
      },
      background: "base",
      style: providerShellStyle,
    },
    [
      hc(
        "div",
        {
          get "data-comparison-color-scheme"() {
            return colorScheme();
          },
          get "data-comparison-action-count"() {
            return String(actionCount());
          },
          get "data-comparison-button-props"() {
            return serializeButtonDemoProps(demoProps());
          },
        },
        [hc("div", { class: "comparison-button-row" }, [renderedButton])],
      ),
    ],
  );
}

function SolidSpectrumActionButtonDemo() {
  const [actionCount, setActionCount] = createSignal(0);
  const [demoProps, setDemoProps] = createSignal(actionButtonDemoPropsFromWindow());
  const [colorScheme, setColorScheme] = createSignal<ComparisonResolvedTheme>(
    getComparisonResolvedThemeFromDocument(),
  );

  onMount(() => {
    const handleControlsChange = (event: Event) => {
      if (event instanceof CustomEvent && event.detail?.component === "actionbutton") {
        setDemoProps(event.detail.props as ActionButtonDemoProps);
      }
    };
    const handleThemeChange = (event: Event) => {
      if (event instanceof CustomEvent && event.detail?.resolvedTheme) {
        setColorScheme(event.detail.resolvedTheme as ComparisonResolvedTheme);
      }
    };
    window.addEventListener(comparisonControlsEvent, handleControlsChange);
    window.addEventListener(comparisonThemeChangeEvent, handleThemeChange);
    setColorScheme(getComparisonResolvedThemeFromDocument());
    onCleanup(() => {
      window.removeEventListener(comparisonControlsEvent, handleControlsChange);
      window.removeEventListener(comparisonThemeChangeEvent, handleThemeChange);
    });
  });

  const renderedActionButton = createMemo(() => {
    const props = demoProps();

    return hc(
      SolidSpectrumActionButton,
      {
        size: props.size,
        staticColor: props.staticColor,
        isQuiet: props.isQuiet,
        isDisabled: props.isDisabled,
        isPending: props.isPending,
        ...(props.iconPlacement === "only" ? { "aria-label": props.children } : {}),
        onPress: (_event: unknown) => {
          if (!props.isPending) {
            setActionCount((count) => count + 1);
          }
        },
      },
      solidSingleButtonFamilyChildren(props.children, props.iconPlacement, () =>
        s2ActionButtonText({ isProgressVisible: props.isPending }),
      ),
    );
  });

  return hc(
    SolidSpectrumProvider,
    {
      get colorScheme() {
        return colorScheme();
      },
      background: "base",
      style: providerShellStyle,
    },
    [
      hc(
        "div",
        {
          class: "comparison-button-row",
          get "data-comparison-color-scheme"() {
            return colorScheme();
          },
          get "data-comparison-action-count"() {
            return String(actionCount());
          },
          get "data-comparison-actionbutton-props"() {
            return serializeActionButtonDemoProps(demoProps());
          },
          get "data-comparison-actionbutton-pending"() {
            return demoProps().isPending ? "true" : undefined;
          },
        },
        [renderedActionButton],
      ),
    ],
  );
}

function SolidSpectrumActionButtonGroupDemo() {
  const [selectedKeys, setSelectedKeys] = createSignal<Set<string>>(new Set(["bold"]));
  const [actionKey, setActionKey] = createSignal("");
  const selectedKeyText = createMemo(() => Array.from(selectedKeys()).join(","));
  const toggleKey = (key: string) => {
    setActionKey(key);
    setSelectedKeys(new Set([key]));
  };

  return hc(
    SolidSpectrumProvider,
    { colorScheme: "dark", background: "base", style: providerShellStyle },
    [
      hc(
        "div",
        {
          get "data-comparison-action-key"() {
            return actionKey();
          },
          get "data-comparison-selected-keys"() {
            return selectedKeyText();
          },
        },
        [
          hc(
            SolidSpectrumActionButtonGroup,
            { "aria-label": "Formatting actions" },
            actionItems.map((item: ActionItem) =>
              hc(
                SolidSpectrumActionButton,
                {
                  get "aria-pressed"() {
                    return selectedKeys().has(item.id);
                  },
                  onPress: (_event: unknown) => toggleKey(item.id),
                },
                [item.label],
              ),
            ),
          ),
        ],
      ),
    ],
  );
}

function SolidSpectrumButtonGroupDemo() {
  const [actionKey, setActionKey] = createSignal("");

  return hc(
    SolidSpectrumProvider,
    { colorScheme: "dark", background: "base", style: providerShellStyle },
    [
      hc(
        "div",
        {
          get "data-comparison-action-key"() {
            return actionKey();
          },
        },
        [
          hc(SolidSpectrumButtonGroup, { "aria-label": "Approval actions" }, [
            hc(
              SolidSpectrumButton,
              {
                variant: "primary",
                onPress: (_event: unknown) => setActionKey("save"),
              },
              ["Save"],
            ),
            hc(
              SolidSpectrumButton,
              {
                variant: "secondary",
                onPress: (_event: unknown) => setActionKey("cancel"),
              },
              ["Cancel"],
            ),
          ]),
        ],
      ),
    ],
  );
}

function SolidSpectrumLinkButtonDemo() {
  const [colorScheme, setColorScheme] = createSignal<ComparisonResolvedTheme>(
    getComparisonResolvedThemeFromDocument(),
  );
  const iconPlacement = iconPlacementFromWindow();

  onMount(() => {
    const handleThemeChange = (event: Event) => {
      if (event instanceof CustomEvent && event.detail?.resolvedTheme) {
        setColorScheme(event.detail.resolvedTheme as ComparisonResolvedTheme);
      }
    };
    window.addEventListener(comparisonThemeChangeEvent, handleThemeChange);
    setColorScheme(getComparisonResolvedThemeFromDocument());
    onCleanup(() => window.removeEventListener(comparisonThemeChangeEvent, handleThemeChange));
  });

  return hc(
    SolidSpectrumProvider,
    {
      get colorScheme() {
        return colorScheme();
      },
      background: "base",
      style: providerShellStyle,
    },
    [
      hc(
        "div",
        {
          class: "comparison-button-row",
          get "data-comparison-color-scheme"() {
            return colorScheme();
          },
        },
        [
          hc(
            SolidSpectrumLinkButton,
            {
              href: "https://example.com/docs",
              variant: "primary",
              fillStyle: "fill",
              ...(iconPlacement === "only" ? { "aria-label": "Open docs" } : {}),
            },
            solidSingleButtonFamilyChildren("Open docs", iconPlacement, () =>
              s2ButtonText({ isProgressVisible: false }),
            ),
          ),
        ],
      ),
    ],
  );
}

function SolidSpectrumToggleButtonDemo() {
  const iconPlacement = iconPlacementFromWindow();
  const [selected, setSelected] = createSignal(booleanParamFromWindow("isSelected"));

  return hc(
    SolidSpectrumProvider,
    { colorScheme: "dark", background: "base", style: providerShellStyle },
    [
      hc(
        "div",
        {
          get "data-comparison-selected"() {
            return String(selected());
          },
        },
        [
          hc(
            SolidSpectrumToggleButton,
            {
              ...(iconPlacement === "only" ? { "aria-label": "Pin" } : {}),
              get isSelected() {
                return selected();
              },
              onChange: setSelected,
            },
            solidSingleButtonFamilyChildren("Pin", iconPlacement, () => s2ToggleButtonText),
          ),
        ],
      ),
    ],
  );
}

function SolidSpectrumToggleButtonGroupDemo() {
  const [selectedKeys, setSelectedKeys] = createSignal<Set<string>>(new Set(["left"]));
  const [colorScheme, setColorScheme] = createSignal<ComparisonResolvedTheme>(
    getComparisonResolvedThemeFromDocument(),
  );
  const selectedKeyText = createMemo(() => Array.from(selectedKeys()).join(","));

  onMount(() => {
    const handleThemeChange = (event: Event) => {
      if (event instanceof CustomEvent && event.detail?.resolvedTheme) {
        setColorScheme(event.detail.resolvedTheme as ComparisonResolvedTheme);
      }
    };
    window.addEventListener(comparisonThemeChangeEvent, handleThemeChange);
    setColorScheme(getComparisonResolvedThemeFromDocument());
    onCleanup(() => window.removeEventListener(comparisonThemeChangeEvent, handleThemeChange));
  });

  return hc(
    SolidSpectrumProvider,
    {
      get colorScheme() {
        return colorScheme();
      },
      background: "base",
      style: providerShellStyle,
    },
    [
      hc(
        "div",
        {
          get "data-comparison-color-scheme"() {
            return colorScheme();
          },
          get "data-comparison-selected-keys"() {
            return selectedKeyText();
          },
        },
        [
          hc(
            SolidSpectrumToggleButtonGroup,
            {
              "aria-label": "Text alignment",
              selectionMode: "single",
              get selectedKeys() {
                return selectedKeys();
              },
              onSelectionChange: (keys: Set<string | number>) =>
                setSelectedKeys(new Set(Array.from(keys, String))),
            },
            [
              hc(SolidSpectrumToggleButton, { id: "left" }, ["Left"]),
              hc(SolidSpectrumToggleButton, { id: "center" }, ["Center"]),
              hc(SolidSpectrumToggleButton, { id: "right" }, ["Right"]),
            ],
          ),
        ],
      ),
    ],
  );
}

function SolidSpectrumSegmentedControlDemo() {
  const [selectedKey, setSelectedKey] = createSignal("list");
  const [colorScheme, setColorScheme] = createSignal<ComparisonResolvedTheme>(
    getComparisonResolvedThemeFromDocument(),
  );

  onMount(() => {
    const handleThemeChange = (event: Event) => {
      if (event instanceof CustomEvent && event.detail?.resolvedTheme) {
        setColorScheme(event.detail.resolvedTheme as ComparisonResolvedTheme);
      }
    };
    window.addEventListener(comparisonThemeChangeEvent, handleThemeChange);
    setColorScheme(getComparisonResolvedThemeFromDocument());
    onCleanup(() => window.removeEventListener(comparisonThemeChangeEvent, handleThemeChange));
  });

  return hc(
    SolidSpectrumProvider,
    {
      get colorScheme() {
        return colorScheme();
      },
      background: "base",
      style: providerShellStyle,
    },
    [
      hc(
        "div",
        {
          get "data-comparison-color-scheme"() {
            return colorScheme();
          },
          get "data-comparison-selected-key"() {
            return selectedKey();
          },
        },
        [
          hc(
            SolidSpectrumSegmentedControl,
            {
              "aria-label": "View mode",
              get selectedKey() {
                return selectedKey();
              },
              onSelectionChange: (key: string | number) => setSelectedKey(String(key)),
            },
            [
              hc(SolidSpectrumSegmentedControlItem, { id: "list" }, ["List"]),
              hc(SolidSpectrumSegmentedControlItem, { id: "grid" }, ["Grid"]),
              hc(SolidSpectrumSegmentedControlItem, { id: "board" }, ["Board"]),
            ],
          ),
        ],
      ),
    ],
  );
}

function SolidSpectrumSelectBoxGroupDemo() {
  const [selectedKeys, setSelectedKeys] = createSignal<Set<string>>(new Set(["starter"]));
  const [colorScheme, setColorScheme] = createSignal<ComparisonResolvedTheme>(
    getComparisonResolvedThemeFromDocument(),
  );
  const selectedKeyText = createMemo(() => Array.from(selectedKeys()).join(","));

  onMount(() => {
    const handleThemeChange = (event: Event) => {
      if (event instanceof CustomEvent && event.detail?.resolvedTheme) {
        setColorScheme(event.detail.resolvedTheme as ComparisonResolvedTheme);
      }
    };
    window.addEventListener(comparisonThemeChangeEvent, handleThemeChange);
    setColorScheme(getComparisonResolvedThemeFromDocument());
    onCleanup(() => window.removeEventListener(comparisonThemeChangeEvent, handleThemeChange));
  });

  return hc(
    SolidSpectrumProvider,
    {
      get colorScheme() {
        return colorScheme();
      },
      background: "base",
      style: providerShellStyle,
    },
    [
      hc(
        "div",
        {
          get "data-comparison-color-scheme"() {
            return colorScheme();
          },
          get "data-comparison-selected-keys"() {
            return selectedKeyText();
          },
        },
        [
          hc(
            SolidSpectrumSelectBoxGroup,
            {
              "aria-label": "Plans",
              orientation: "horizontal",
              items: selectBoxItems,
              getKey: (item: (typeof selectBoxItems)[number]) => item.id,
              getTextValue: (item: (typeof selectBoxItems)[number]) => item.label,
              get selectedKeys() {
                return selectedKeys();
              },
              onSelectionChange: (keys: "all" | Set<string | number>) =>
                setSelectedKeys(
                  keys === "all" ? new Set<string>() : new Set<string>(Array.from(keys, String)),
                ),
            },
            renderProp((item: (typeof selectBoxItems)[number]) =>
              hc(SolidSpectrumSelectBox, { id: item.id, textValue: item.label }, [
                hc("strong", {}, [item.label]),
                hc("span", {}, [item.description]),
              ]),
            ),
          ),
        ],
      ),
    ],
  );
}

function SolidSpectrumCardViewDemo() {
  const [selectedKeys, setSelectedKeys] = createSignal<Set<string>>(new Set(["apollo"]));
  const [colorScheme, setColorScheme] = createSignal<ComparisonResolvedTheme>(
    getComparisonResolvedThemeFromDocument(),
  );
  const selectedKeyText = createMemo(() => Array.from(selectedKeys()).join(","));

  onMount(() => {
    const handleThemeChange = (event: Event) => {
      if (event instanceof CustomEvent && event.detail?.resolvedTheme) {
        setColorScheme(event.detail.resolvedTheme as ComparisonResolvedTheme);
      }
    };
    window.addEventListener(comparisonThemeChangeEvent, handleThemeChange);
    setColorScheme(getComparisonResolvedThemeFromDocument());
    onCleanup(() => window.removeEventListener(comparisonThemeChangeEvent, handleThemeChange));
  });

  return hc(
    SolidSpectrumProvider,
    {
      get colorScheme() {
        return colorScheme();
      },
      background: "base",
      style: providerShellStyle,
    },
    [
      hc(
        "div",
        {
          get "data-comparison-color-scheme"() {
            return colorScheme();
          },
          get "data-comparison-selected-keys"() {
            return selectedKeyText();
          },
        },
        [
          hc(
            SolidSpectrumCardView,
            {
              "aria-label": "Projects",
              items: cardItems,
              getKey: (item: (typeof cardItems)[number]) => item.id,
              getTextValue: (item: (typeof cardItems)[number]) => item.title,
              size: "S",
              density: "compact",
              variant: "secondary",
              selectionMode: "single",
              selectionStyle: "highlight",
              UNSAFE_style: cardViewDemoStyle,
              get selectedKeys() {
                return selectedKeys();
              },
              onSelectionChange: (keys: "all" | Set<string | number>) =>
                setSelectedKeys(
                  keys === "all" ? new Set<string>() : new Set<string>(Array.from(keys, String)),
                ),
            },
            renderProp((item: (typeof cardItems)[number]) =>
              hc(SolidSpectrumCard, {}, [
                hc("strong", {}, [item.title]),
                " ",
                hc("span", {}, [item.status]),
              ]),
            ),
          ),
        ],
      ),
    ],
  );
}

const providerShellStyle = {
  padding: 0,
  background: "transparent",
};

const cardViewDemoStyle = {
  width: "360px",
  height: "180px",
};

const nestedProviderStyle = {
  padding: "16px",
  margin: "16px 0 0",
  "border-radius": "16px",
};
