// apps/comparison/src/scripts/solid-mount.tsx
import { render } from "solid-js/web";
import ComparisonIsland from "../components/solid/ComparisonIsland.tsx";
import type {
  ComparisonLayerId,
  ComparisonSlug,
} from "../data/comparison-manifest";

for (
  const mountNode of document.querySelectorAll<HTMLElement>(".js-solid-mount")
) {
  if (mountNode.dataset.mounted) {
    continue;
  }

  mountNode.dataset.mounted = "true";
  const componentSlug = mountNode.dataset.componentSlug as
    | ComparisonSlug
    | undefined;
  const layer = mountNode.dataset.layer as ComparisonLayerId | undefined;

  if (!componentSlug || !layer) {
    continue;
  }

  render(
    () =>
      ComparisonIsland({
        componentSlug,
        layer,
      }),
    mountNode,
  );
}

// apps/comparison/src/scripts/react-mount.tsx
import React from "react";
import { createRoot } from "react-dom/client";
import ComparisonIsland from "../components/react/ComparisonIsland.jsx";

for (const mountNode of document.querySelectorAll<HTMLElement>(".js-react-mount")) {
  if (mountNode.dataset.mounted) {
    continue;
  }

  mountNode.dataset.mounted = "true";
  createRoot(mountNode).render(
    React.createElement(ComparisonIsland, {
      componentSlug: mountNode.dataset.componentSlug,
      layer: mountNode.dataset.layer,
    }),
  );
}
